import * as z from "zod";

// things

export const ClientSchema = z
	.object({
		id: z.string(),
		razao: z.string(),
		fantasia: z.string(),
		cnpj_cpf: z.string(),
		tipo_pessoa: z.string(),
		email: z.string(),
		fone: z.string(),
		telefone_celular: z.string(),
		whatsapp: z.string(),
		endereco: z.string(),
		numero: z.string(),
		complemento: z.string(),
		bairro: z.string(),
		cidade: z.string(),
		uf: z.string(),
		cep: z.string(),
		ativo: z.string(),
		data_cadastro: z.string(),
		// vo bota tudo nao man
	})
	.loose();

export const ContractSchema = z.object({
	id_instalador: z.string(),
	indicacao_contrato_id: z.string(),
	id_indexador_reajuste: z.string(),
	data_desistencia: z.string(),
	motivo_desistencia: z.string(),
	obs_desistencia: z.string(),
	obs_contrato: z.string(),
	alerta_contrato: z.string(),
	ids_contratos_recorrencia: z.string(),
	id_responsavel_desistencia: z.string(),
	id_responsavel_cancelamento: z.string(),
	id_responsavel_negativacao: z.string(),
	origem_cancelamento: z.string(),
	situacao_financeira_contrato: z.string(),
	dt_ult_desbloq_auto: z.string(),
	dt_ult_desbloq_manual: z.string(),
	aplicar_desconto_tempo_bloqueio: z.string(),
	tempo_permanencia: z.string(),
	id: z.string(),
	id_filial: z.string(),
	status: z.string(),
	status_internet: z.string(),
	id_cliente: z.string(),
	data_assinatura: z.string(),
	data_ativacao: z.string(),
	data: z.string(),
	data_renovacao: z.string(),
	bloqueio_automatico: z.string(),
	imp_carteira: z.string(),
	data_expiracao: z.string(),
	isentar_contrato: z.string(),
	pago_ate_data: z.string(),
	id_vd_contrato: z.string(),
	contrato: z.string(),
	endereco: z.string(),
	numero: z.string(),
	comissao: z.string(),
	bairro: z.string(),
	tipo: z.string(),
	descricao_aux_plano_venda: z.string(),
	aviso_atraso: z.string(),
	id_tipo_contrato: z.string(),
	id_carteira_cobranca: z.string(),
	obs: z.string(),
	id_modelo: z.string(),
	status_velocidade: z.string(),
	id_vendedor: z.string(),
	cc_previsao: z.string(),
	nao_avisar_ate: z.string(),
	nao_bloquear_ate: z.string(),
	id_tipo_documento: z.string(),
	tipo_doc_opc: z.string(),
	desconto_fidelidade: z.string(),
	tipo_doc_opc2: z.string(),
	tipo_doc_opc3: z.string(),
	taxa_improdutiva: z.string(),
	tipo_doc_opc4: z.string(),
	desbloqueio_confianca: z.string(),
	data_negativacao: z.string(),
	data_acesso_desativado: z.string(),
	motivo_cancelamento: z.string(),
	data_cancelamento: z.string(),
	obs_cancelamento: z.string(),
	id_vendedor_ativ: z.string(),
	fidelidade: z.string(),
	tipo_cobranca: z.string(),
	desbloqueio_confianca_ativo: z.string(),
	id_responsavel: z.string(),
	taxa_instalacao: z.string(),
	protocolo_negativacao: z.string(),
	dt_ult_bloq_auto: z.string(),
	dt_ult_bloq_manual: z.string(),
	dt_ult_des_bloq_conf: z.string(),
	dt_ult_ativacao: z.string(),
	avalista_1: z.string(),
	dt_ult_finan_atraso: z.string(),
	avalista_2: z.string(),
	dt_utl_negativacao: z.string(),
	data_cadastro_sistema: z.string(),
	ultima_atualizacao: z.string(),
	complemento: z.string(),
	cep: z.string(),
	imp_importacao: z.string(),
	cidade: z.string(),
	imp_rede: z.string(),
	renovacao_automatica: z.string(),
	imp_bkp: z.string(),
	imp_treinamento: z.string(),
	id_motivo_inclusao: z.string(),
	imp_status: z.string(),
	motivo_inclusao: z.string(),
	imp_obs: z.string(),
	liberacao_bloqueio_manual: z.string(),
	imp_realizado: z.string(),
	contrato_suspenso: z.string(),
	imp_motivo: z.string(),
	imp_inicial: z.string(),
	imp_final: z.string(),
	ativacao_numero_parcelas: z.string(),
	ativacao_vencimentos: z.string(),
	ativacao_valor_parcela: z.string(),
	id_tipo_doc_ativ: z.string(),
	id_produto_ativ: z.string(),
	id_cond_pag_ativ: z.string(),
	endereco_padrao_cliente: z.string(),
	referencia: z.string(),
	id_condominio: z.string(),
	nf_info_adicionais: z.string(),
	assinatura_digital: z.string(),
	tipo_produtos_plano: z.string(),
	bloco: z.string(),
	apartamento: z.string(),
	latitude: z.string(),
	longitude: z.string(),
	num_parcelas_atraso: z.string(),
	dt_ult_desiste: z.string(),
	id_contrato_principal: z.string(),
	gerar_finan_assin_digital_contrato: z.string(),
	credit_card_recorrente_token: z.string(),
	credit_card_recorrente_bandeira_cartao: z.string(),
	id_motivo_negativacao: z.string(),
	obs_negativacao: z.string(),
	restricao_auto_desbloqueio: z.string(),
	motivo_restricao_auto_desbloq: z.string(),
	nao_susp_parc_ate: z.string(),
	liberacao_suspensao_parcial: z.string(),
	utilizando_auto_libera_susp_parc: z.string(),
	restricao_auto_libera_susp_parcial: z.string(),
	motivo_restri_auto_libera_parc: z.string(),
	data_inicial_suspensao: z.string(),
	data_final_suspensao: z.string(),
	data_retomada_contrato: z.string(),
	dt_ult_liberacao_susp_parc: z.string(),
	base_geracao_tipo_doc: z.string(),
	integracao_assinatura_digital: z.string(),
	url_assinatura_digital: z.string(),
	token_assinatura_digital: z.string(),
	testemunha_assinatura_digital: z.string(),
	document_photo: z.string(),
	selfie_photo: z.string(),
	tipo_localidade: z.string(),
	estrato_social_col: z.string(),
	agrupar_financeiro_contrato: z.string(),
	status_recorrencia: z.string(),
});

export const DepartmentSchema = z.object({
	id: z
		.string()
		.max(11, { message: "Max 11 characters" })
		.regex(/^\d+$/, { message: "Numbers only" }),
	setor: z
		.string()
		.min(1, { message: "Required field" })
		.max(200, { message: "Max 200 characters" }),
	email: z
		.string()
		.max(65535, { message: "Max 65535 characters" })
		.nullable()
		.optional()
		.describe("Can be null"),
	presta_atendimento: z.enum(["S", "N"]).default("S").optional().describe("S = Yes, N = No"),
	mostra_hotsite: z.enum(["S", "N"]).default("S").optional().describe("S = Yes, N = No"),
	exige_vinculo_produto: z.enum(["S", "N"]).default("S").optional().describe("S = Yes, N = No"),
	ordem: z
		.string()
		.min(1, { message: "Required field" })
		.max(15, { message: "Max 15 characters" })
		.default("10")
		.describe("Exhibition order (mask: Array)"),
	ativo: z.enum(["S", "N"]).default("S").optional().describe("S = Yes, N = No"),
});

export const FaturaSchema = z.object({
	id_remessa: z.string(),
	gateway_link: z.string(),
	nn_boleto: z.string(),
	boleto: z.string(),
	data_inicial: z.string(),
	data_final: z.string(),
	estornado: z.string(),
	conta_recebimento: z.string(),
	bandeira_pagamento: z.string(),
	recebido_por_recorrencia: z.string(),
	valor_juros: z.string(),
	valor_multas: z.string(),
	id: z.string(),
	liberado: z.string(),
	filial_id: z.string(),
	status: z.string(),
	data_emissao: z.string(),
	data_vencimento: z.string(),
	valor: z.string(),
	obs: z.string(),
	valor_recebido: z.string(),
	valor_aberto: z.string(),
	id_cliente: z.string(),
	pagamento_valor: z.string(),
	pagamento_data: z.string(),
	id_carteira_cobranca: z.string(),
	credito_data: z.string(),
	baixa_data: z.string(),
	numero_parcela_recorrente: z.string(),
	documento: z.string(),
	id_saida: z.string(),
	tipo_renegociacao: z.string(),
	tipo_recebimento: z.string(),
	valor_cancelado: z.string(),
	data_cancelamento: z.string(),
	id_mot_cancelamento: z.string(),
	previsao: z.string(),
	id_renegociacao: z.string(),
	id_cobranca: z.string(),
	id_renegociacao_novo: z.string(),
	libera_periodo: z.string(),
	impresso: z.string(),
	forma_recebimento: z.string(),
	arquivo_remessa_baixado: z.string(),
	status_cobranca: z.string(),
	nparcela: z.string(),
	id_nota_gerada_opc4: z.string(),
	tipo_cobranca: z.string(),
	id_contrato_principal: z.string(),
	id_nota_gerada: z.string(),
	id_contrato_avulso: z.string(),
	id_im_imovel: z.string(),
	ids_contratos_origem: z.string(),
	id_contrato: z.string(),
	duplicata: z.string(),
	id_sip: z.string(),
	parcela_proporcional: z.string(),
	linha_digitavel: z.string(),
	gerencianet_token: z.string(),
	tipo_pagamento_cartao: z.string(),
	titulo_protestado: z.string(),
	desconto_condicional_valor: z.string(),
	validade_desconto_condicional: z.string(),
	id_conta: z.string(),
	titulo_renegociado: z.string(),
	motivo_alteracao: z.string(),
	id_remessa_alteracao: z.string(),
	cancelamento_id_operador: z.string(),
	baixa_id_operador: z.string(),
	titulo_importado: z.string(),
	origem_importacao: z.string(),
	ultima_atualizacao: z.string(),
	aguardando_confirmacao_pagamento: z.string(),
	parcelado_cartao: z.string(),
	pix_txid: z.string(),
	id_nota_gerada_opc2: z.string(),
	id_nota_gerada_opc3: z.string(),
	recebido_via_pix: z.string(),
	id_lote_geracao_financeiro_fatura: z.string(),
	pix_txid_recorrente: z.string(),
	pix_status_recorrente: z.string(),
	tipo_cobranca_pix: z.string(),
	data_prevista_tentativa_pix_recorrente: z.string(),
	tentativa_pix_recorrente: z.string(),
});

// responses

function ListResponseSchema<T extends z.ZodTypeAny>(item: T) {
	return z
		.object({
			page: z.string().optional(),
			total: z.union([z.string(), z.number()]).optional(),
			registros: z.array(item).optional(),
		})
		.loose();
}

export const ListClientResponseSchema = ListResponseSchema(ClientSchema);
export const ListContractResponseSchema = ListResponseSchema(ContractSchema);
export const ListDepartmentsResponseSchema = ListResponseSchema(DepartmentSchema);
export const ListFaturasResponseSchema = ListResponseSchema(FaturaSchema);

// fields

export const DocumentSchema = z
	.string()
	.min(1, "Document is required")
	.refine(
		(doc) =>
			/^\d{3}\.\d{3}\.\d{3}-\d{2}$/.test(doc) || // CPF
			/^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/.test(doc), // CNPJ
		{
			message: "Document must be formatted.",
		},
	);
